### ISSUE TITLE
Russian mod translation

### ISSUE THREAD

**Issue by dmg-b** [Dplayend/Merge-Enchantments#1]
[ru_ru.zip](https://github.com/Dplayend/Merge-Enchantments/files/8878834/ru_ru.zip)

translated by dmg_b

**Comment by Dplayend** [comment]
nice job, i will put it in the v1.5 of the mod

**Comment by Dplayend** [comment]
i made the v1.5 with a lot of new things, can you make again the traslated for the new words?
here is the lang updated
[https://github.com/Dplayend/Merge-Enchantments/blob/1.18.x-fabric/src/main/resources/assets/merenc/lang/en_us.json](url)
