### ISSUE TITLE
Game crashes if viewing a pickaxe with both fortune and silk touch and silk touch is turned off

### ISSUE THREAD

**Issue by HarvardHa123** [Dplayend/Merge-Enchantments#3]
As stated in the title, if silky touch is off and I view the pickaxe, the game crashes. Link to crash report: https://paste.ubuntu.com/p/DPGsrC9mGV/plain/. I don't have to many mods, they may be slightly clashing, and I am horrible at troubleshooting, and this is all I could find.

**Comment by Dplayend** [comment]
i install the mods and i see you have "no-enchant-cap-1.18.1-fabric-2.1.1" in the 1.19 version of minecraft fabric

**Comment by HarvardHa123** [comment]
thank you so much, I just updated the mod to the 1.19 version
