### ISSUE TITLE
Tetra compatible

### ISSUE THREAD

**Issue by Dr-WeiAL** [Dplayend/Merge-Enchantments#7]
Silk Touch is not displayed in Tooltips, although it can be toggled on Tetra tools.
![image](https://user-images.githubusercontent.com/47446553/193433351-7873e2b9-0c08-4922-a13c-89f47209bf96.png)
![image](https://user-images.githubusercontent.com/47446553/193433357-dc620913-27be-45b5-bf97-b6c0eeed9d05.png)
![image](https://user-images.githubusercontent.com/47446553/193433364-f1e51de0-11b2-44b1-bfa8-217dc75a1911.png)

**Comment by Dplayend** [comment]
Merge Enchantments not support Tetra mod, because with Tetra when you put an enchantment this had his own tooltip enchant method
