### ISSUE TITLE
No xp when is enchanted with disabled silk touch

### ISSUE THREAD

**Issue by Lui22b** [Dplayend/Merge-Enchantments#9]
![image](https://user-images.githubusercontent.com/72612000/197869178-ee4be2e1-ca4d-4009-9c07-39235a7965ca.png)

![image](https://user-images.githubusercontent.com/72612000/197869293-e23ab8b2-f65d-4152-b664-4528de387c3b.png)

![image](https://user-images.githubusercontent.com/72612000/197869483-b977d7be-8211-4d61-b2d1-47b27f0b7bc1.png)

**Comment by Lui22b** [comment]
It is on fabric

**Comment by Dplayend** [comment]
I thing other mod cause that problem, I tested in forge and fabric on all versions that I made
![2023-07-18_18 04 19](https://github.com/Dplayend/Merge-Enchantments/assets/69760998/25c2b245-547f-4b75-bdc7-3a440a6745c0)
